M48
; DRILL file {KiCad (6.0.7)} date Mon Oct 31 18:53:31 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-31T18:53:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X3.675Y-3.66
X4.2754Y-3.6481
X4.305Y-4.05
T2
X2.4455Y-1.2564
X2.4455Y-2.5595
X5.0045Y-1.2564
X5.0045Y-2.5595
T0
M30
